name: baywatch_lint
description: A set of custom_lint rules that provides alerts on methods and patterns and that can be replaced by nullsafety alternative
version: 0.0.1
repository: https://github.com/evaisse/dart_baywatch_lint

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ">=0.5.7"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


